Assistance msg
raccoongang/EdxAdaptXBlock pull request #3
Opened 2016-11-30 14:10 UTC by idegtiarov

Add editable fields for messages when user is enrolled successfully  and unsuccessfully.

2016-12-22 14:17 UTC, z4y4ts requested changes

2016-12-22 14:17 UTC, z4y4ts commented on edxadapt/edxadapt.py
> +        display_name=_("Congrats with successful registeration"),
"Successful EdxAdapt registration message"

2016-12-22 14:17 UTC, z4y4ts commented on edxadapt/edxadapt.py
> +        help=_("Congrats message student see after successfully enrolled in Edx Adapt"),
"Message displayed to student after successful registration in EdxAdapt."

2016-12-22 14:17 UTC, z4y4ts commented on edxadapt/edxadapt.py
> +            "Successfully registered in Edx Adapt, course is completely ready to start."
"Your adaptive learning session is configured now. Please click Next button to start solve problems."

2016-12-22 14:17 UTC, z4y4ts commented on edxadapt/edxadapt.py
> +        display_name=_("Assistance message if enrollment fails"),
"Failed EdxAdapt registration message"

2016-12-22 14:17 UTC, z4y4ts commented on edxadapt/edxadapt.py
>              self=self,
`self` is not used in html, can be removed

2016-12-22 14:17 UTC, z4y4ts commented on edxadapt/edxadapt.py
> +            student_is_registered=self.student_is_registered,
`student_is_registered` is not used in html, can be removed

2016-12-22 14:40 UTC, idegtiarov commented on edxadapt/edxadapt.py
> +            "Successfully registered in Edx Adapt, course is completely ready to start."
done

2016-12-22 14:40 UTC, idegtiarov commented on edxadapt/edxadapt.py
> +        display_name=_("Congrats with successful registeration"),
done

2016-12-22 14:42 UTC, idegtiarov commented on edxadapt/edxadapt.py
> +        help=_("Congrats message student see after successfully enrolled in Edx Adapt"),
done

2016-12-22 14:42 UTC, idegtiarov commented on edxadapt/edxadapt.py
> +        display_name=_("Assistance message if enrollment fails"),
done

2016-12-22 14:42 UTC, idegtiarov commented on edxadapt/edxadapt.py
>              self=self,
done

2016-12-22 14:42 UTC, idegtiarov commented on edxadapt/edxadapt.py
> +            student_is_registered=self.student_is_registered,
done

2016-12-23 16:31 UTC, z4y4ts commented on edxadapt/edxadapt.py
> +                    'params': self.params,
Hold on. I though we've moved `params` and `skills` into html template. Looks like merging went wrong.

Or do I miss something?

2016-12-26 07:43 UTC, idegtiarov commented on edxadapt/edxadapt.py
> +                    'params': self.params,
That is weird, I am checking

2016-12-26 11:33 UTC, z4y4ts approved these changes
You may want to make long lines comply with the code style. The rest looks good.

Make sure to squash it.

2016-12-26 11:33 UTC, z4y4ts commented on edxadapt/edxadapt.py
> +    editable_fields = ('params', 'skills', 'edx_adapt_api_url', 'success_registration_msg', 'fail_registration_msg')
I guess it's about time to split this long line.

2016-12-26 13:36 UTC, idegtiarov commented on edxadapt/edxadapt.py
> +    editable_fields = ('params', 'skills', 'edx_adapt_api_url', 'success_registration_msg', 'fail_registration_msg')
All line's length is less than 120 chars which is recommended by edx, so I suppose splitting is not needed.

2016-12-26 13:36 UTC, merged